import { Mulish } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/Sidebar';

const mulish = Mulish({
  subsets: ['latin'],
  variable: '--font-mulish',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.variable}>
      <body className="font-mulish antialiased flex">
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
